### ISSUE TITLE
. = today() 

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-xpathjs#27]
e.g. today should return a date type so that the expression:

. = today() 

starts working properly for an input with xml type date.

**Comment by willywutang** [comment]
Any hope of fixing this?

**Comment by MartijnR** [comment]
Yes, but it will require one of Enketo's donors to start pushing for this. I think Esri will probably want to add this to the todo list, but not sure when it will be a priority for them.

**Comment by MartijnR** [comment]
The date widget gets today's date as '2018-06-25' which is the local date.

**Comment by MartijnR** [comment]
* [ ] add new tests
* [ ] check/fix/change failing tests
* [ ] reproduce in Enketo Core
* [ ] check fix in Enketo Core in different timezones

**Comment by MartijnR** [comment]
Issue:

We want 2018-01-02 to convert to a whole number, which means **it is in GMT**.

However, when we collect today's date with a date widget, or with the today() function, we want the local date.

Therefore there is a conflict with making the constraint ". < today()" work as desired.

**Comment by MartijnR** [comment]
I think the only reasonable to solution is to accept that 2018-01-02 will be considered a local date, and therefore return a different value depending on the timezone of the user.
