### ISSUE TITLE
Remove benchmarks

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-xpathjs#45]
Opening `benchmark/` in a browser, I get the following error:
> 404 Not Found: http://localhost:8080/tests/tests.php

To reproduce:
1. start php server in project root directory with `php -S localhost:8080`
2. open `http://localhost:8080/benchmark/` in a browser

This seems to be fixable by:
1. copy `tests/` dir from https://github.com/andrejpavlovic/xpathjs
2. copy `build/enketo-xpathjs.min.js` to `build/xpathjs.min.js`

**Comment by alxndrsn** [comment]
Also seem to be able to start the server with `grunt`, but the result is the same.

**Comment by MartijnR** [comment]
Ah yes, thanks. I should remove the benchmarks. They have no value, because they refer to native when available and don't include the custom functions I added.
