### ISSUE TITLE
argument support for uuid()

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-xpathjs#55]

**Comment by MartijnR** [comment]
https://github.com/opendatakit/javarosa/blob/master/core/src/org/javarosa/core/util/PropertyUtils.java#L60

**Comment by MartijnR** [comment]
https://opendatakit.github.io/xforms-spec/#fn:uuid

There is now an expressed desire for this: https://forum.opendatakit.org/t/generate-identifier-of-specific-length-to-link-forms/20700

**Comment by MartijnR** [comment]
ping @vimemo, in case you'd like to squeeze this one in :)

**Comment by vimemo** [comment]
hi @MartijnR, will do. I should also be completing a list of expressions that I need to discuss with you before the end of this week (some minor differences in current browser implementations and such). Thank you.

**Comment by MartijnR** [comment]
Great! I'll be available. Thanks
