### ISSUE TITLE
today() + 14 no longer returning a datestring but a number

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-xpathjs#58]
Seen in Chrome. Could be caused by browser update.

**Comment by tedrick** [comment]
I also saw it in Safari

**Comment by MartijnR** [comment]
Not sure what I was thinking. This has always been the case.

**Comment by MartijnR** [comment]
in ODK Collect:

10 + "2012-07-24" returns no result (probably NaN)
10 + date("2012-0-24") = 15555
today()+10 as date = crash
today()+10 as string = 17238

**Comment by MartijnR** [comment]
Maybe enketo-core could convert numbers to dates. It seems like Enketo does things correctly though.

**Comment by MartijnR** [comment]
yep, seems like this should be done when setting a value in the model in Enketo Core
