### ISSUE TITLE
boolean() return true for empty nodeset

### ISSUE THREAD

**Issue by tiritea** [enketo/enketo-xpathjs#85]
boolean() function appears to always return true for a nodeset argument, even when its empty. Whereas according XPAth spec it should return false for an empty node:

> The boolean function converts its argument to a boolean as follows:
> ...
>     a node-set is true if and only if it is non-empty
>

**Comment by MartijnR** [comment]
Thanks! I have in the past thought [the same as you](https://github.com/andrejpavlovic/xpathjs/issues/1).

A node-set is only empty if it doesn't return nodes, i.e. the nodes do not exist. The text content of the nodes is not taking into consideration.

I have a nice codepen for that (using browser's native XPath evaluator): https://codepen.io/MartijnR/pen/YJaBdQ
